# **CH 08 넘파이 소개 및 기초 사용법**

- 넘파이 라이브러리에 대해 소개하고 배열을 생성해본다.
- 데이터형을 확인해보고 배열의 형태를 바꾸어본다.
- 배열의 인덱싱과 슬라이싱 방법을 배운다.
- 넘파이의 정렬을 해본다
- 배열의 연산에 대해 배운다.

## SECTION 01 넘파이 소개

### 넘파이 개념

In [2]:
# 수치 데이터를 다루기 위한 라이브러리
# 배열 계산에 최적화, 빠른 처리 속도

import numpy as np
print(np.__version__)

1.22.4


### 넘파이 배열

In [3]:
# 리스트 : 다양한 값을 연속으로 저장하는 데이터형
# 넘파이 배열 : 데이터 분석에 주로 사용하는 데이터형
# 데이터 프레임 : 데이터 전처리에 주로 사용하는 데이터형

In [4]:
d = np.arange(12).reshape(3,4)
print(d, d.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)


In [5]:
d.ndim

2

In [6]:
d.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [7]:
d.size

12

In [8]:
d.nbytes

96

In [9]:
d.flat = 1
d

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [10]:
mynp1 = np.array([1,2,3])
print(type(mynp1))

<class 'numpy.ndarray'>


In [11]:
mylist2 = [[1,2,3,],[4,5,6,]]
print(type(mylist2))

mynpa2 = np.array(mylist2)
print(type(mynpa2))

<class 'list'>
<class 'numpy.ndarray'>


In [12]:
import pandas as pd

mypd1 = pd.DataFrame = ([1,2,3])

mynp1 = np.array(mypd1)
print(type(mynp1))

<class 'numpy.ndarray'>


### 1차원 넘파이 배열 생성

In [13]:
import numpy as np

a = np.arange(3)
print(a, type(a), a.ndim, a.shape)

[0 1 2] <class 'numpy.ndarray'> 1 (3,)


### 2차원 넘파이 배열 생성

In [14]:
m = np.array([np.arange(3), np.arange(3,6)])
print(m, m.shape)

[[0 1 2]
 [3 4 5]] (2, 3)


### 3차원 넘파이 배열 생성

In [15]:
m = np.array([[[0,1,2],[3,4,5]],[[0,1,2],[3,4,5]]])

print(m)

print(m.shape)

[[[0 1 2]
  [3 4 5]]

 [[0 1 2]
  [3 4 5]]]
(2, 2, 3)


In [16]:
m = np.array([np.arange(0,4,3),np.arange(1,5,3),np.arange(2,6,3)])

print(m)

[[0 3]
 [1 4]
 [2 5]]


In [17]:
m = np.array([[[0,1],[2,3]],[[4,5],[6,7]],[[8,9],[10,11]]])

print(m)
print(m.shape)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
(3, 2, 2)


## SECTION 02 배열 다루기

### 배열의 데이터형 확인과 변형

In [18]:
import numpy as np

nda = np.array([0,1,2,3,4,5])
print(nda, type(nda))
print(nda.dtype)
nda

[0 1 2 3 4 5] <class 'numpy.ndarray'>
int64


array([0, 1, 2, 3, 4, 5])

In [19]:
a1 = np.array(['1.2', '2.3', '3.4', '4.5'])
print(a1, a1.dtype)

a2 = a1.astype('float32')
print(a2, a2.dtype)

a3 = a2.astype('int32')
print(a3, a3.dtype)

a3 = a1.astype('int32')
print(a3, a3.dttype)

['1.2' '2.3' '3.4' '4.5'] <U3
[1.2 2.3 3.4 4.5] float32
[1 2 3 4] int32


ValueError: ignored

### 배열의 형태 변경

In [20]:
m1 = np.arange(6)
print(m1)
print(m1.shape)

[0 1 2 3 4 5]
(6,)


In [21]:
m2 = m1.reshape(6, 1)
print(m2, m2.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]] (6, 1)


In [22]:
m2 = m1.reshape(2, 3)
print(m2, m2.shape)

[[0 1 2]
 [3 4 5]] (2, 3)


In [23]:
m1 = np.arange(12)

m3 = m1.reshape(2,2,3)
print(m3, m3.shape)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]] (2, 2, 3)


In [24]:
m1 = np.arange(6)

m2 = m1. reshape(-1,2)
print(m2, m2.shape)

m2 = m1.reshape(-1, 3)
print(m2, m2.shape)

m2 = m1.reshape(-1, 1)
print(m2, m2.shape)


[[0 1]
 [2 3]
 [4 5]] (3, 2)
[[0 1 2]
 [3 4 5]] (2, 3)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]] (6, 1)


In [25]:
m1 = np.arange(6)

m3 = m1. reshape(-1,2,3)
print(m3, m3.shape)

m3 = m1.reshape(-1, 3, 2)
print(m3, m3.shape)

m3 = m1.reshape(2,3,-1)
print(m3, m3.shape)

[[[0 1 2]
  [3 4 5]]] (1, 2, 3)
[[[0 1]
  [2 3]
  [4 5]]] (1, 3, 2)
[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]] (2, 3, 1)


### 다차원의 배열을 1차원 배열로 평탄화하기

In [26]:
a = np.arange(12).reshape(3,4)

f = a.flatten()

In [27]:
print(a)

print(a.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### 배열의 통합과 분할

In [28]:
a = np.arange(9).reshape(3,3)

b = a * 2
print(a)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [29]:
r = np.vstack((a,b))
print(r, r.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]] (6, 3)


In [30]:
c = np.row_stack((a,b))
print(c, c.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]] (6, 3)


In [31]:
x = np.concatenate((a,b), axis = 0)
print(x, x.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]] (6, 3)


In [32]:
import random

In [33]:
r = np.hstack((a, b))
print(r, r.shape)

[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]] (3, 6)


In [38]:
c = np.column_stack((a, b))
print(c, c.shape)

[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]] (3, 6)


In [36]:
x = np.concatenate((a, b), axis = 1)
print(x, x.shape)

[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]] (3, 6)


In [42]:
a = np.arange(12).reshape(4, 3)

In [44]:
print(np.vsplit(a, 4))

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]]), array([[ 9, 10, 11]])]


In [46]:
a = np.arange(12).reshape(3, 4)

In [47]:
print(np.hsplit(a, 4))

[array([[0],
       [4],
       [8]]), array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


## SECTION 03 배열의 인덱싱과 슬라이싱



### 1차원 배열의 인덱싱과 슬라이싱