# **CH 08 넘파이 소개 및 기초 사용법**

- 넘파이 라이브러리에 대해 소개하고 배열을 생성해본다.
- 데이터형을 확인해보고 배열의 형태를 바꾸어본다.
- 배열의 인덱싱과 슬라이싱 방법을 배운다.
- 넘파이의 정렬을 해본다
- 배열의 연산에 대해 배운다.

## SECTION 01 넘파이 소개

### 넘파이 개념

In [ ]:
# 수치 데이터를 다루기 위한 라이브러리
# 배열 계산에 최적화, 빠른 처리 속도

import numpy as np
print(np.__version__)

1.22.4


### 넘파이 배열

In [ ]:
# 리스트 : 다양한 값을 연속으로 저장하는 데이터형
# 넘파이 배열 : 데이터 분석에 주로 사용하는 데이터형
# 데이터 프레임 : 데이터 전처리에 주로 사용하는 데이터형

In [ ]:
d = np.arange(12).reshape(3,4)
print(d, d.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)


In [ ]:
d.ndim

2

In [ ]:
d.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
d.size

12

In [ ]:
d.nbytes

96

In [ ]:
d.flat = 1
d

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
mynp1 = np.array([1,2,3])
print(type(mynp1))

<class 'numpy.ndarray'>


In [ ]:
mylist2 = [[1,2,3,],[4,5,6,]]
print(type(mylist2))

mynpa2 = np.array(mylist2)
print(type(mynpa2))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
import pandas as pd

mypd1 = pd.DataFrame = ([1,2,3])

mynp1 = np.array(mypd1)
print(type(mynp1))

<class 'numpy.ndarray'>


### 1차원 넘파이 배열 생성

In [ ]:
import numpy as np

a = np.arange(3)
print(a, type(a), a.ndim, a.shape)

[0 1 2] <class 'numpy.ndarray'> 1 (3,)


### 2차원 넘파이 배열 생성

In [ ]:
m = np.array([np.arange(3), np.arange(3,6)])
print(m, m.shape)

[[0 1 2]
 [3 4 5]] (2, 3)


### 3차원 넘파이 배열 생성

In [ ]:
m = np.array([[[0,1,2],[3,4,5]],[[0,1,2],[3,4,5]]])

print(m)

print(m.shape)

[[[0 1 2]
  [3 4 5]]

 [[0 1 2]
  [3 4 5]]]
(2, 2, 3)


In [ ]:
m = np.array([np.arange(0,4,3),np.arange(1,5,3),np.arange(2,6,3)])

print(m)

[[0 3]
 [1 4]
 [2 5]]


In [ ]:
m = np.array([[[0,1],[2,3]],[[4,5],[6,7]],[[8,9],[10,11]]])

print(m)
print(m.shape)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
(3, 2, 2)


## SECTION 02 배열 다루기

### 배열의 데이터형 확인과 변형

In [ ]:
import numpy as np

nda = np.array([0,1,2,3,4,5])
print(nda, type(nda))
print(nda.dtype)
nda

[0 1 2 3 4 5] <class 'numpy.ndarray'>
int64


array([0, 1, 2, 3, 4, 5])

In [ ]:
a1 = np.array(['1.2', '2.3', '3.4', '4.5'])
print(a1, a1.dtype)

a2 = a1.astype('float32')
print(a2, a2.dtype)

a3 = a2.astype('int32')
print(a3, a3.dtype)

a3 = a1.astype('int32')
print(a3, a3.dttype)

['1.2' '2.3' '3.4' '4.5'] <U3
[1.2 2.3 3.4 4.5] float32
[1 2 3 4] int32


ValueError: ignored

### 배열의 형태 변경

In [ ]:
m1 = np.arange(6)
print(m1)
print(m1.shape)

[0 1 2 3 4 5]
(6,)


In [ ]:
m2 = m1.reshape(6, 1)
print(m2, m2.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]] (6, 1)


In [ ]:
m2 = m1.reshape(2, 3)
print(m2, m2.shape)

[[0 1 2]
 [3 4 5]] (2, 3)


In [ ]:
m1 = np.arange(12)

m3 = m1.reshape(2,2,3)
print(m3, m3.shape)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]] (2, 2, 3)


In [ ]:
m1 = np.arange(6)

m2 = m1. reshape(-1,2)
print(m2, m2.shape)

m2 = m1.reshape(-1, 3)
print(m2, m2.shape)

m2 = m1.reshape(-1, 1)
print(m2, m2.shape)


[[0 1]
 [2 3]
 [4 5]] (3, 2)
[[0 1 2]
 [3 4 5]] (2, 3)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]] (6, 1)


In [ ]:
m1 = np.arange(6)

m3 = m1. reshape(-1,2,3)
print(m3, m3.shape)

m3 = m1.reshape(-1, 3, 2)
print(m3, m3.shape)

m3 = m1.reshape(2,3,-1)
print(m3, m3.shape)

[[[0 1 2]
  [3 4 5]]] (1, 2, 3)
[[[0 1]
  [2 3]
  [4 5]]] (1, 3, 2)
[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]] (2, 3, 1)


### 다차원의 배열을 1차원 배열로 평탄화하기

In [ ]:
a = np.arange(12).reshape(3,4)

f = a.flatten()

In [ ]:
print(a)

print(a.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### 배열의 통합과 분할

In [ ]:
a = np.arange(9).reshape(3,3)

b = a * 2
print(a)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [ ]:
r = np.vstack((a,b))
print(r, r.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]] (6, 3)


In [ ]:
c = np.row_stack((a,b))
print(c, c.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]] (6, 3)


In [ ]:
x = np.concatenate((a,b), axis = 0)
print(x, x.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]] (6, 3)


In [ ]:
import random

In [ ]:
r = np.hstack((a, b))
print(r, r.shape)

[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]] (3, 6)


In [ ]:
c = np.column_stack((a, b))
print(c, c.shape)

[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]] (3, 6)


In [ ]:
x = np.concatenate((a, b), axis = 1)
print(x, x.shape)

[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]] (3, 6)


In [ ]:
a = np.arange(12).reshape(4, 3)

In [ ]:
print(np.vsplit(a, 4))

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]]), array([[ 9, 10, 11]])]


In [ ]:
a = np.arange(12).reshape(3, 4)

In [ ]:
print(np.hsplit(a, 4))

[array([[0],
       [4],
       [8]]), array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


## SECTION 03 배열의 인덱싱과 슬라이싱



### 1차원 배열의 인덱싱과 슬라이싱

In [ ]:

d = np.arange(6)
print(d, d.shape)

[0 1 2 3 4 5] (6,)


In [ ]:
print(d[0],d[1],d[2],d[-1],d[-2])

0 1 2 5 4


In [ ]:
print(d[2:3], d[:],d[:-1])
print(d[::2], d[::-1])
d[0] = 10
print(d)

[2] [0 1 2 3 4 5] [0 1 2 3 4]
[0 2 4] [5 4 3 2 1 0]
[10  1  2  3  4  5]


### 2차원 배열의 인덱싱과 슬라이싱

In [ ]:
d = np.arange(12).reshape(3, 4)
print(d, d.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)


In [ ]:
print(d[0][1])
print(d[0,1])
print(d[2,1])

1
1
9


In [ ]:
print(d[0])
print(d[0,:])
print(d[:,:-1])
print(d[::2,::2])

[0 1 2 3]
[0 1 2 3]
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]
[[ 0  2]
 [ 8 10]]


In [ ]:
d[0] = 20
print(d)

[[20 20 20 20]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
d[::2,::3] = 30
print(d[::2,::3])
print(d)

[[30 30]
 [30 30]]
[[30 20 20 30]
 [ 4  5  6  7]
 [30  9 10 30]]


In [ ]:
d[:,:] = -1
print(d)

[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


### 3차원 배열의 인덱싱과 슬라이싱

In [58]:
d = np.arange(12).reshape(2,2,3)
print(d, d.shape)

print(d[0][0][0])
print(d[0,0,0])
print(d[0,1,2])

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]] (2, 2, 3)
0
0
5


In [60]:
print(d[:,:-1,:-1])

[[[0 1]]

 [[6 7]]]


In [61]:
print(d[:,1:,1:])

[[[ 4  5]]

 [[10 11]]]


In [63]:
print(d[:,-1,-1])
print(d[-1,-1,-1])

[ 5 11]
11


In [64]:
a = np.arange(12)
print(a, a.shape)
print(a[0])
print(a[0:1])

[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)
0
[0]


### 볼 인덱싱

In [69]:
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [70]:
print(a[a>2])

[3 4 5 6]


### 조건 필터

In [72]:
a = np.array([1,2,3,4,5,6])
result = a > 2
result

array([False, False,  True,  True,  True,  True])

In [73]:
a[a != 3]

array([1, 2, 4, 5, 6])

In [75]:
print(a[(a > 2) & (a < 6)])
print(a[a % 2 == 0])
print(a[a < a.mean()])

[3 4 5]
[2 4 6]
[1 2 3]


In [81]:
a = np.array([1,2,3,4,5,6])
b = np.array([])

In [82]:
print(b[True])
print(b[False])

[]
[]


## SECTION 04 넘파이 배열의 정렬

### 기본 정렬

In [84]:
a = np.array([2,8,9,7,3,1,4,5,6])
print(a, a.shape)
r = np.sort(a)
print(r, a)

[2 8 9 7 3 1 4 5 6] (9,)
[1 2 3 4 5 6 7 8 9] [2 8 9 7 3 1 4 5 6]


In [85]:
a.sort()
print(a)

[1 2 3 4 5 6 7 8 9]


In [86]:
r = np.sort(a)[::-1]
print(r)

[9 8 7 6 5 4 3 2 1]


### 인덱스 반환 정렬

In [88]:
a = np.array([2,8,9,7,3,1,4,5,6])
print(a, a.shape)

[2 8 9 7 3 1 4 5 6] (9,)


In [89]:
np.argsort(a)

array([5, 0, 4, 6, 7, 8, 3, 1, 2])

In [91]:
sort_index = np.argsort(a)
print(a[sort_index])

[1 2 3 4 5 6 7 8 9]


### 2차원 배열의 정렬

In [92]:
arr2d = np. array([[5,6,7,8],
                   [4,3,2,1],
                   [10,9,12,11]])

print(arr2d)

[[ 5  6  7  8]
 [ 4  3  2  1]
 [10  9 12 11]]


In [93]:
print(arr2d.shape)

(3, 4)


In [94]:
# 열방향

np.sort(arr2d, axis = 1)

array([[ 5,  6,  7,  8],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [95]:
np.sort(arr2d, axis = 0)

array([[ 4,  3,  2,  1],
       [ 5,  6,  7,  8],
       [10,  9, 12, 11]])

In [96]:
print(arr2d)
print(np.sort(arr2d))
np.argsort(arr2d, axis = 1)


[[ 5  6  7  8]
 [ 4  3  2  1]
 [10  9 12 11]]
[[ 5  6  7  8]
 [ 1  2  3  4]
 [ 9 10 11 12]]


array([[0, 1, 2, 3],
       [3, 2, 1, 0],
       [1, 0, 3, 2]])

In [97]:
print(arr2d)
print(np.sort(arr2d, axis = 0))
np.argsort(arr2d, axis = 0)

[[ 5  6  7  8]
 [ 4  3  2  1]
 [10  9 12 11]]
[[ 4  3  2  1]
 [ 5  6  7  8]
 [10  9 12 11]]


array([[1, 1, 1, 1],
       [0, 0, 0, 0],
       [2, 2, 2, 2]])

## SECTION 05 넘파이 배열의 연산

### 배열과 스칼라(상수) 간이 연산

In [100]:
a = np.array([[1,2,3],
              [4,5,6]])

np.sum(a, axis = 0), np.sum(a, axis = 1)

(array([5, 7, 9]), array([ 6, 15]))

In [101]:
a.sum()

21

In [103]:
a = np.array([[1,2,3],
              [4,5,6]])

b = 2
print(a + b)
print(a - b)
print(a / b)
print(a * b)


[[3 4 5]
 [6 7 8]]
[[-1  0  1]
 [ 2  3  4]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]]
[[ 2  4  6]
 [ 8 10 12]]


In [104]:
A = np.arange(1,13).reshape(3,4)

print(A + 10)
print(A - 10)
print(A * 10)
print(A / 10)



[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]
[[-9 -8 -7 -6]
 [-5 -4 -3 -2]
 [-1  0  1  2]]
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
[[0.1 0.2 0.3 0.4]
 [0.5 0.6 0.7 0.8]
 [0.9 1.  1.1 1.2]]


In [105]:
A = np.arange(1, 13).reshape(3, 4)
A - 1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [106]:
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([1,2,3])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[[2 4 6]
 [5 7 9]]
[[0 0 0]
 [3 3 3]]
[[ 1  4  9]
 [ 4 10 18]]
[[1.  1.  1. ]
 [4.  2.5 2. ]]


In [108]:
a = np.array([[1,2],
              [3,4]])

b = np.array([[1,2],
              [1,2]])

print(a * b) # 배열의 곱셈
print(a.dot(b)) #행렬의 곱셈

[[1 4]
 [3 8]]
[[ 3  6]
 [ 7 14]]


### 브로드캐스팅

In [109]:
A = np.array([[1,2],
              [3,4]])

B = np.array([1,2])

A + B

array([[2, 4],
       [4, 6]])

In [113]:
A = np.array([[1,2,3],
              [4,5,6]])

B = np.array([[2],
              [4]])

A + B

array([[ 3,  4,  5],
       [ 8,  9, 10]])

# 문제

In [116]:
import numpy as np

In [118]:
a = np.arange(3)
print(a)

[0 1 2]


In [119]:
for i in range(1,6,2) :
  print(i)

1
3
5


In [120]:
arr = np.arange(start = 1, stop = 11, step = 1)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [122]:
m = np.array([[0,1,2],
              [3,4,5]])
print(m.shape)

(2, 3)


In [123]:
arr1 = np.array([1,2,3,3.14])
print(arr1.dtype)

float64


In [124]:
m1 = np.arange(6)
m2 = m1.reshape(6,1)

print(m2.shape)

(6, 1)


In [125]:
a = np.arange(12).reshape(3, 4)
f = a.flatten()

print(f, f.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)


In [126]:
d = np.arange(6)
print(d[-2])

4


In [127]:
a = np.arange(1,7)
a[[1,3,5,2]]

array([2, 4, 6, 3])